name: Update Components

# Run every 4 hours, or manually
on:
  schedule:
    - cron: "0 0 * * *" # Every 24 hours
  workflow_dispatch: # Allow manual triggering
  push:
    paths:
      - "data/repos.json" # Also run when repos.json changes
      - "scripts/build-components.js" # Also run when build-components.js changes

jobs:
  update-components:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Allows pushing code changes
      pages: write # Allows deploying to GitHub Pages
      id-token: write # Required by peaceiris/actions-gh-pages

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Build component index
        run: npm run build-components
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check for changes
        id: verify-changed-files
        run: |
          if git diff --quiet docs/components.json; then
            echo "No changes detected"
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "Changes detected in components.json"
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push changes
        if: steps.verify-changed-files.outputs.changed == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add docs/components.json
          git commit -m "🤖 Auto-update: New changes detected"
          git push

      - name: Deploy to GitHub Pages
        if: steps.verify-changed-files.outputs.changed == 'true'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
